### ISSUE TITLE
Default location: swiftlint.path

### ISSUE THREAD

**Issue by Zingam** [vknabel/vscode-apple-swift-format#17]
The extensions after reset appear to set the default locations to

```
"apple-swift-format.path": "/usr/local/bin/swift-format"
"swiftlint.path": "/usr/local/bin/swiftlint"
```

I think it's more reasonable and portable to set the default values without the path and to expect to find them in the search path

```
"apple-swift-format.path": "swift-format"
"swiftlint.path": "swiftlint"
```

**Comment by vknabel** [comment]
Hey @Zingam. Thanks for your suggestion.

I decided to allow user to set the paths as Strings, but also as array of strings.
The default will be `["/usr/bin/env", "swift$TOOL"]`. I will release all extensions in one go later.

**Comment by vknabel** [comment]
Has been released:
- https://github.com/vknabel/vscode-swiftlint/releases/tag/1.8.0
- https://github.com/vknabel/vscode-swiftformat/releases/tag/1.6.0
- https://github.com/vknabel/vscode-apple-swift-format/releases/tag/1.4.0
