### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by SARAsBooks** [vknabel/vscode-apple-swift-format#31]
ChartsView.swift: error: Unable to open /usr/bin/env: file is not readable or does not exist <unknown>: error: Unable to open swift-format: file is not readable or does not exist

swift-format build was successful and path in configuration file to swift-format.exe was given.

**Comment by angel-luis** [comment]
In  my case the error is `Could not find apple/swift-format: /usr/bin/env swift-format` and I've installed `swift-format` with the MSI package and the command is available inside VSC, so it seems a plugin problem.

**Comment by vknabel** [comment]
Hey, sorry for the late response! As a quick question: what happens if you prefix your local windows path with a `/` like:

```
"apple-swift-format.path": ["/C:/Library/Developer/Tools/swift-format.exe", "swift-format"]
                          // ^ here
```

In case it works for you, I could create a fix for this issue

**Comment by angel-luis** [comment]
Unfortunately I moved to MacOS so I don't work anymore with Windows, but this can remain visible to future Windows users having the same trouble.

**Comment by vknabel** [comment]
Will probably be solved the same as https://github.com/vknabel/vscode-swiftlint/issues/67

**Comment by vknabel** [comment]
Should be fixed in current release
